#include "enif.hpp"

namespace arterial {

using ::nifpp::am_error;
using ::nifpp::am_false;
using ::nifpp::am_nil;
using ::nifpp::am_ok;
using ::nifpp::am_true;
using ::nifpp::am_undefined;

NIFPP_ADD_KNOWN_ATOM(am_add_membership);
NIFPP_ADD_KNOWN_ATOM(am_alloc_failed);
NIFPP_ADD_KNOWN_ATOM(am_app_version);
NIFPP_ADD_KNOWN_ATOM(am_arterial_accept);
NIFPP_ADD_KNOWN_ATOM(am_arterial_disconnected);
NIFPP_ADD_KNOWN_ATOM(am_arterial_event);
NIFPP_ADD_KNOWN_ATOM(am_arterial_fifo_reply);
NIFPP_ADD_KNOWN_ATOM(am_arterial_reply);
NIFPP_ADD_KNOWN_ATOM(am_arterial_timeout);
NIFPP_ADD_KNOWN_ATOM(am_backend);
NIFPP_ADD_KNOWN_ATOM(am_bad_protocol);
NIFPP_ADD_KNOWN_ATOM(am_closed);
NIFPP_ADD_KNOWN_ATOM(am_connect_failed);
NIFPP_ADD_KNOWN_ATOM(am_connect_result);
NIFPP_ADD_KNOWN_ATOM(am_connecting);
NIFPP_ADD_KNOWN_ATOM(am_cork);
NIFPP_ADD_KNOWN_ATOM(am_drop_membership);
NIFPP_ADD_KNOWN_ATOM(am_epoll);
NIFPP_ADD_KNOWN_ATOM(am_failed_to_set_nonblocking);
NIFPP_ADD_KNOWN_ATOM(am_fifo_disabled);
NIFPP_ADD_KNOWN_ATOM(am_fifo_draining);
NIFPP_ADD_KNOWN_ATOM(am_fifo_not_enabled);
NIFPP_ADD_KNOWN_ATOM(am_fifo_request_sent);
NIFPP_ADD_KNOWN_ATOM(am_fifo_reserved);
NIFPP_ADD_KNOWN_ATOM(am_fifo_slot_busy);
NIFPP_ADD_KNOWN_ATOM(am_invalid_option);
NIFPP_ADD_KNOWN_ATOM(am_invalid_reservation);
NIFPP_ADD_KNOWN_ATOM(am_io_uring);
NIFPP_ADD_KNOWN_ATOM(am_keepalive);
NIFPP_ADD_KNOWN_ATOM(am_keepcnt);
NIFPP_ADD_KNOWN_ATOM(am_keepidle);
NIFPP_ADD_KNOWN_ATOM(am_keepintvl);
NIFPP_ADD_KNOWN_ATOM(am_kqueue);
NIFPP_ADD_KNOWN_ATOM(am_linger);
NIFPP_ADD_KNOWN_ATOM(am_max_slots_exceeded_64);
NIFPP_ADD_KNOWN_ATOM(am_multicast_if);
NIFPP_ADD_KNOWN_ATOM(am_multicast_join_failed);
NIFPP_ADD_KNOWN_ATOM(am_multicast_leave_failed);
NIFPP_ADD_KNOWN_ATOM(am_multicast_loop);
NIFPP_ADD_KNOWN_ATOM(am_multicast_ttl);
NIFPP_ADD_KNOWN_ATOM(am_nodelay);
NIFPP_ADD_KNOWN_ATOM(am_not_fifo);
NIFPP_ADD_KNOWN_ATOM(am_not_implemented);
NIFPP_ADD_KNOWN_ATOM(am_optimization);
NIFPP_ADD_KNOWN_ATOM(am_prod);
NIFPP_ADD_KNOWN_ATOM(am_profile);
NIFPP_ADD_KNOWN_ATOM(am_partial);
NIFPP_ADD_KNOWN_ATOM(am_pgo);
NIFPP_ADD_KNOWN_ATOM(am_pool_busy);
NIFPP_ADD_KNOWN_ATOM(am_priority);
NIFPP_ADD_KNOWN_ATOM(am_quickack);
NIFPP_ADD_KNOWN_ATOM(am_rcvbuf);
NIFPP_ADD_KNOWN_ATOM(am_rcvlowat);
NIFPP_ADD_KNOWN_ATOM(am_reactor_init_failed);
NIFPP_ADD_KNOWN_ATOM(am_read);
NIFPP_ADD_KNOWN_ATOM(am_recvbuf);
NIFPP_ADD_KNOWN_ATOM(am_reuseaddr);
NIFPP_ADD_KNOWN_ATOM(am_select_failed);
NIFPP_ADD_KNOWN_ATOM(am_sndbuf);
NIFPP_ADD_KNOWN_ATOM(am_sndlowat);
NIFPP_ADD_KNOWN_ATOM(am_socket_failed);
NIFPP_ADD_KNOWN_ATOM(am_socket_option_failed);
NIFPP_ADD_KNOWN_ATOM(am_ssl_not_supported);
NIFPP_ADD_KNOWN_ATOM(am_ssl);
NIFPP_ADD_KNOWN_ATOM(am_stop);
NIFPP_ADD_KNOWN_ATOM(am_stripe_full);
NIFPP_ADD_KNOWN_ATOM(am_test);
NIFPP_ADD_KNOWN_ATOM(am_tcp);
NIFPP_ADD_KNOWN_ATOM(am_timeout_setup_failed);
NIFPP_ADD_KNOWN_ATOM(am_timeout);
NIFPP_ADD_KNOWN_ATOM(am_tos);
NIFPP_ADD_KNOWN_ATOM(am_udp);
NIFPP_ADD_KNOWN_ATOM(am_unknown);
NIFPP_ADD_KNOWN_ATOM(am_unsupported_protocol);
NIFPP_ADD_KNOWN_ATOM(am_user_timeout);
NIFPP_ADD_KNOWN_ATOM(am_version);
NIFPP_ADD_KNOWN_ATOM(am_write_failed);
NIFPP_ADD_KNOWN_ATOM(am_write);

} // namespace arterial